[build-system]
requires      = ["setuptools>=63.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rainbow-api"
version = "1.0.6"
description = "Read chromatography and mass spectrometry binary files"
readme = "README.md"
license = {text = "COPYING"}
authors = [
    {name = "Evan Shi and Eugene Kwan"},
    {email = "evanyshi@cmu.edu"}
]
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)"
]
dependencies = [
    "numpy",
    "matplotlib",
    "lxml"
]

[project.urls]
Repository = "https://github.com/evanyeyeye/rainbow"
Documentation = "https://rainbow-api.readthedocs.io"
